apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: test.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Webapp is the Schema for the webapps API
      displayName: Webapp
      kind: Webapp
      name: webapps.webappgroup.venkateshsredhat.com
      version: v1alpha1
  description: operator built to try out the openshift operator framework
  displayName: webapp-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - webapp
  - venkatesh_s
  links:
  - name: Test
    url: https://test.domain
  maturity: alpha
  provider:
    name: ves@redhat.com
  version: 0.0.0
